# Stage 1: Build the React app
FROM node:18-alpine as build

WORKDIR /app

# Copy the package.json and package-lock.json (for npm)
COPY package.json package-lock.json ./

# Set the build argument for Vite
ARG VITE_API_BASE_URL

# Install dependencies using npm
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the React app, passing VITE_API_BASE_URL as an environment variable to the build process
RUN VITE_API_BASE_URL=$VITE_API_BASE_URL npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine

# Copy the built React app from the previous stage to the Nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
